# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Verify RC

on:
  push:
    branches:
      - "!**"
    tags:
      - "*-rc*"

permissions:
  contents: read

jobs:
  source:
    name: Source on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
        postgresql-version:
          - "15"
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          ci/scripts/prepare-${{ matrix.os }}.sh ${{ matrix.postgresql-version }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
          cache-version: 1
      - name: Run
        run: |
          version=${GITHUB_REF_NAME%-rc*}
          rc=${GITHUB_REF_NAME#*-rc}
          bundle exec dev/release/verify-rc.sh ${version} ${rc}
        env:
          TEST_DEFAULT: "0"
          TEST_SOURCE: "1"

  binaries:
    name: Binaries
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          version=${GITHUB_REF_NAME%-rc*}
          rc=${GITHUB_REF_NAME#*-rc}
          dev/release/verify-rc.sh ${version} ${rc}
        env:
          TEST_BINARIES: "1"
          TEST_DEFAULT: "0"
